# Generated by Django 2.1.2 on 2019-02-17 00:48

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.fields import ArrayField

class Migration(migrations.Migration):

    #initial = True

    #dependencies = [
        #('datasets', '0019_auto_20190217_0048'),
        #migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    #]

    #dependencies = [
        #('main', '0011_auto_20190110_1807'),
    #]

    operations = [
        migrations.AddField(
            model_name='placewhen',
            name='minmax',
            field=ArrayField(models.IntegerField(blank=True,null=True))
        ),
    ]
