# Generated by Django 2.1.2 on 2019-01-01 20:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_auto_20181231_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='ccodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), default=[], size=None),
            preserve_default=False,
        ),
    ]
