# Generated by Django 2.1.2 on 2019-01-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0005_auto_20190102_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='type',
            field=models.CharField(choices=[('user', 'User drawn'), ('region', 'Region/Polity record'), ('ccodes', 'Country codes')], max_length=20),
        ),
    ]
