# Generated by Django 2.1.2 on 2019-01-05 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0006_auto_20190105_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 1, 5, 23, 9, 12, 127071)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='type',
            field=models.CharField(choices=[('ccodes', 'Country codes'), ('region', 'Region/Polity record'), ('user', 'User drawn')], max_length=20),
        ),
    ]
