# Generated by Django 2.1.2 on 2019-01-08 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0007_auto_20190105_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='geom',
            new_name='geojson',
        ),
    ]
