# Generated by Django 2.1.2 on 2019-01-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0008_auto_20190108_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
