# Generated by Django 2.1.2 on 2018-11-06 19:08

import contribute.models
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('tgn', 'Getty TGN'), ('dbp', 'DBpedia'), ('gn', 'Geonames'), ('wd', 'Wikidata'), ('spine', 'WHG Spine')], max_length=64)),
                ('base_uri', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'authorities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique='True')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2044)),
                ('file', models.FileField(upload_to=contribute.models.user_directory_path)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('delimited', 'Delimited'), ('lpf', 'Linked Places json-l')], default='delimited', max_length=12)),
                ('datatype', models.CharField(choices=[('place', 'Places'), ('anno', 'Annotations'), ('source', 'Sources')], default='place', max_length=12)),
                ('delimiter', models.CharField(blank=True, max_length=2, null=True)),
                ('status', models.CharField(blank=True, choices=[('format_error', 'Invalid format'), ('format_ok', 'Valid format'), ('uploaded', 'Uploaded'), ('ready', 'Ready for submittal'), ('accepted', 'Accepted')], max_length=12, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('accepted_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('mapbox_id', models.CharField(blank=True, max_length=200, null=True)),
                ('header', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None)),
                ('numrows', models.IntegerField(blank=True, null=True)),
                ('numlinked', models.IntegerField(blank=True, null=True)),
                ('total_links', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'datasets',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authrecord_id', models.CharField(max_length=64)),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hits',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_id', models.CharField(max_length=24)),
                ('authrecord_id', models.CharField(max_length=64)),
                ('match_type', models.CharField(choices=[('tgn', 'Getty TGN'), ('dbp', 'DBpedia'), ('gn', 'Geonames'), ('wd', 'Wikidata'), ('spine', 'WHG Spine')], max_length=12)),
                ('review_note', models.CharField(blank=True, max_length=2044, null=True)),
                ('flag_geom', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('authority', models.ForeignKey(db_column='authority', on_delete='models.CASCADE', to='contribute.Authority')),
            ],
            options={
                'db_table': 'links',
                'managed': True,
            },
        ),
    ]
