# Generated by Django 2.1.2 on 2018-10-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='mapbox_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='status',
            field=models.CharField(blank=True, choices=[('uploaded', 'Uploaded, valid format'), ('ready', 'Ready for submittal'), ('accepted', 'Accepted')], max_length=12, null=True),
        ),
    ]
