# Generated by Django 2.1.2 on 2018-11-06 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
        ('contribute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='place_id',
            field=models.ForeignKey(on_delete='models.CASCADE', to='main.Place'),
        ),
        migrations.AddField(
            model_name='hit',
            name='authority',
            field=models.ForeignKey(db_column='authority', on_delete='models.CASCADE', to='contribute.Authority'),
        ),
        migrations.AddField(
            model_name='hit',
            name='place_id',
            field=models.ForeignKey(on_delete='models.CASCADE', to='main.Place'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL),
        ),
    ]
