# Generated by Django 2.1.2 on 2018-10-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0004_auto_20181027_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='datatype',
            field=models.CharField(choices=[('place', 'Places'), ('anno', 'Annotations'), ('source', 'Sources')], default='place', max_length=12),
        ),
    ]
