# Generated by Django 2.1.2 on 2018-10-27 23:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0005_auto_20181027_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='delimiter',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='header',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30, null=True), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='numrows',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataset',
            name='format',
            field=models.CharField(choices=[('csv', 'CSV'), ('delimited', 'Delimited'), ('lpf', 'Linked Places json-l')], default='delimited', max_length=12),
        ),
    ]
