# Generated by Django 2.1.2 on 2018-10-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0006_auto_20181027_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='numlinked',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='total_links',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
