# Generated by Django 2.1.2 on 2018-10-31 16:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0007_auto_20181028_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='header',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None),
        ),
    ]
