# Generated by Django 2.1.2 on 2018-10-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0008_auto_20181031_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='numlinked',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='numrows',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='total_links',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
