# Generated by Django 2.1.2 on 2018-11-06 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0009_auto_20181031_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hit',
            old_name='placeid',
            new_name='place_id',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='placeid',
            new_name='place_id',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL),
        ),
    ]
