# Generated by Django 2.1.2 on 2018-10-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dataset_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='upload',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='created',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='modified',
        ),
        migrations.AddField(
            model_name='dataset',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
