# Generated by Django 2.1.2 on 2018-11-14 17:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181113_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='ccode',
        ),
        migrations.AddField(
            model_name='place',
            name='ccodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), default=[], size=None),
            preserve_default=False,
        ),
    ]
