# Generated by Django 2.1.2 on 2018-12-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181114_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='placelink',
            name='review_note',
            field=models.CharField(blank=True, max_length=2044, null=True),
        ),
        migrations.AddField(
            model_name='placelink',
            name='task_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
