# Generated by Django 2.1.2 on 2018-10-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_dataset_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='datatype',
            field=models.CharField(choices=[('place', 'Place data'), ('anno', 'Annotations')], default='place', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='format',
            field=models.CharField(choices=[('csv', 'Simple CSV'), ('lpf', 'Linked Places format')], default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='map_uri',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
