# Generated by Django 2.1.2 on 2018-12-24 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181224_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='src_id',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='placegeom',
            name='geom_src',
            field=models.ForeignKey(db_column='dataset', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Source', to_field='src_id'),
        ),
    ]
