# Generated by Django 2.1.2 on 2018-10-23 21:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181021_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceDepiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'place_depiction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlaceDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'place_description',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlaceGeom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'place_geom',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlaceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'place_link',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlaceName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'place_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlaceRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'place_related',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'place_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlaceWhen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'place_when',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='user',
        ),
        migrations.AlterField(
            model_name='place',
            name='dataset',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='place',
            name='src_id',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
        migrations.AddField(
            model_name='placewhen',
            name='placeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Place'),
        ),
        migrations.AddField(
            model_name='placetype',
            name='placeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Place'),
        ),
        migrations.AddField(
            model_name='placerelated',
            name='placeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Place'),
        ),
        migrations.AddField(
            model_name='placename',
            name='placeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Place'),
        ),
        migrations.AddField(
            model_name='placelink',
            name='placeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Place'),
        ),
        migrations.AddField(
            model_name='placegeom',
            name='placeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Place'),
        ),
        migrations.AddField(
            model_name='placedescription',
            name='placeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Place'),
        ),
        migrations.AddField(
            model_name='placedepiction',
            name='placeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Place'),
        ),
    ]
