# Generated by Django 2.1.2 on 2018-12-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181224_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='placegeom',
            name='task_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placename',
            name='task_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
