# Generated by Django 2.1.2 on 2018-12-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181226_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedescription',
            name='task_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
