# Generated by Django 2.1.2 on 2018-10-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181025_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='placename',
            name='toponym',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
