# Generated by Django 2.1.2 on 2018-10-26 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_placename_toponym'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='ccode',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='dataset',
            field=models.ForeignKey(db_column='dataset', on_delete=django.db.models.deletion.CASCADE, to='contribute.Dataset', to_field='label'),
        ),
        migrations.AlterField(
            model_name='place',
            name='placeid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['src_id', 'dataset'], name='places_src_id_486bf2_idx'),
        ),
    ]
