# Generated by Django 2.1.2 on 2019-01-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_placedescription_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedepiction',
            name='src_id',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='placedescription',
            name='src_id',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='placegeom',
            name='src_id',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='placelink',
            name='src_id',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='placename',
            name='src_id',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='placerelated',
            name='src_id',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='placetype',
            name='src_id',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='placewhen',
            name='src_id',
            field=models.CharField(default='', max_length=24),
        ),
    ]
