# Generated by Django 2.1.2 on 2018-10-27 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0004_auto_20181027_0112'),
        ('main', '0010_auto_20181026_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedepiction',
            name='dataset',
            field=models.ForeignKey(db_column='dataset', default='', on_delete=django.db.models.deletion.CASCADE, to='contribute.Dataset', to_field='label'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placedepiction',
            name='src_id',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placedescription',
            name='dataset',
            field=models.ForeignKey(db_column='dataset', default='', on_delete=django.db.models.deletion.CASCADE, to='contribute.Dataset', to_field='label'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placedescription',
            name='src_id',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placegeom',
            name='dataset',
            field=models.ForeignKey(db_column='dataset', default='', on_delete=django.db.models.deletion.CASCADE, to='contribute.Dataset', to_field='label'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placegeom',
            name='src_id',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placelink',
            name='dataset',
            field=models.ForeignKey(db_column='dataset', default='', on_delete=django.db.models.deletion.CASCADE, to='contribute.Dataset', to_field='label'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placelink',
            name='src_id',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placerelated',
            name='dataset',
            field=models.ForeignKey(db_column='dataset', default='', on_delete=django.db.models.deletion.CASCADE, to='contribute.Dataset', to_field='label'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placerelated',
            name='src_id',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placetype',
            name='dataset',
            field=models.ForeignKey(db_column='dataset', default='', on_delete=django.db.models.deletion.CASCADE, to='contribute.Dataset', to_field='label'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placetype',
            name='src_id',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placewhen',
            name='dataset',
            field=models.ForeignKey(db_column='dataset', default='', on_delete=django.db.models.deletion.CASCADE, to='contribute.Dataset', to_field='label'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placewhen',
            name='src_id',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placename',
            name='dataset',
            field=models.ForeignKey(db_column='dataset', on_delete=django.db.models.deletion.CASCADE, to='contribute.Dataset', to_field='label'),
        ),
    ]
