# Generated by Django 2.1.2 on 2019-01-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190110_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedescription',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='placegeom',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='placelink',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='placename',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
