# Generated by Django 2.1.2 on 2018-10-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181027_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_id', models.CharField(max_length=24)),
                ('uri', models.URLField(blank=True, null=True)),
                ('label', models.CharField(max_length=255)),
                ('citation', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'sources',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='placegeom',
            name='geom_src',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Source'),
        ),
        migrations.AddField(
            model_name='placename',
            name='name_src',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Source'),
        ),
    ]
