# Generated by Django 2.1.2 on 2018-11-03 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_source_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placename',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='placename',
            name='src_id',
        ),
        # migrations.AddField(
        #     model_name='place',
        #     name='id',
        #     field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='place',
            name='dataset',
            field=models.ForeignKey(db_column='dataset', on_delete=django.db.models.deletion.CASCADE, related_name='places', to='contribute.Dataset', to_field='label'),
        ),
        migrations.AlterField(
            model_name='place',
            name='placeid',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='placedepiction',
            name='dataset',
            field=models.ForeignKey(db_column='dataset', on_delete=django.db.models.deletion.CASCADE, related_name='depictions', to='contribute.Dataset', to_field='label'),
        ),
        migrations.AlterField(
            model_name='placedepiction',
            name='placeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Place', to_field='placeid'),
        ),
        migrations.AlterField(
            model_name='placedescription',
            name='dataset',
            field=models.ForeignKey(db_column='dataset', on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='contribute.Dataset', to_field='label'),
        ),
        migrations.AlterField(
            model_name='placedescription',
            name='placeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Place', to_field='placeid'),
        ),
        migrations.AlterField(
            model_name='placegeom',
            name='dataset',
            field=models.ForeignKey(db_column='dataset', on_delete=django.db.models.deletion.CASCADE, related_name='geoms', to='contribute.Dataset', to_field='label'),
        ),
        migrations.AlterField(
            model_name='placegeom',
            name='placeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Place', to_field='placeid'),
        ),
        migrations.AlterField(
            model_name='placelink',
            name='dataset',
            field=models.ForeignKey(db_column='dataset', on_delete=django.db.models.deletion.CASCADE, related_name='links', to='contribute.Dataset', to_field='label'),
        ),
        migrations.AlterField(
            model_name='placelink',
            name='placeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Place', to_field='placeid'),
        ),
        migrations.AlterField(
            model_name='placename',
            name='placeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='main.Place', to_field='placeid'),
        ),
        migrations.AlterField(
            model_name='placerelated',
            name='dataset',
            field=models.ForeignKey(db_column='dataset', on_delete=django.db.models.deletion.CASCADE, related_name='related', to='contribute.Dataset', to_field='label'),
        ),
        migrations.AlterField(
            model_name='placerelated',
            name='placeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Place', to_field='placeid'),
        ),
        migrations.AlterField(
            model_name='placetype',
            name='dataset',
            field=models.ForeignKey(db_column='dataset', on_delete=django.db.models.deletion.CASCADE, related_name='types', to='contribute.Dataset', to_field='label'),
        ),
        migrations.AlterField(
            model_name='placetype',
            name='placeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Place', to_field='placeid'),
        ),
        migrations.AlterField(
            model_name='placewhen',
            name='dataset',
            field=models.ForeignKey(db_column='dataset', on_delete=django.db.models.deletion.CASCADE, related_name='whens', to='contribute.Dataset', to_field='label'),
        ),
        migrations.AlterField(
            model_name='placewhen',
            name='placeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Place', to_field='placeid'),
        ),
    ]
