# Generated by Django 2.1.2 on 2018-11-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20181103_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedepiction',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='placedepiction',
            name='src_id',
        ),
        migrations.RemoveField(
            model_name='placedescription',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='placedescription',
            name='src_id',
        ),
        migrations.RemoveField(
            model_name='placegeom',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='placegeom',
            name='src_id',
        ),
        migrations.RemoveField(
            model_name='placelink',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='placelink',
            name='src_id',
        ),
        migrations.RemoveField(
            model_name='placerelated',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='placerelated',
            name='src_id',
        ),
        migrations.RemoveField(
            model_name='placetype',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='placetype',
            name='src_id',
        ),
        migrations.RemoveField(
            model_name='placewhen',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='placewhen',
            name='src_id',
        ),
        # migrations.AddField(
        #     model_name='place',
        #     name='id',
        #     field=models.AutoField(auto_created=True, default=-1, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
    ]
