# Generated by Django 2.1.2 on 2018-11-06 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20181103_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='placeid',
        ),
        migrations.RemoveField(
            model_name='placedepiction',
            name='placeid',
        ),
        migrations.RemoveField(
            model_name='placedescription',
            name='placeid',
        ),
        migrations.RemoveField(
            model_name='placegeom',
            name='placeid',
        ),
        migrations.RemoveField(
            model_name='placelink',
            name='placeid',
        ),
        migrations.RemoveField(
            model_name='placename',
            name='placeid',
        ),
        migrations.RemoveField(
            model_name='placerelated',
            name='placeid',
        ),
        migrations.RemoveField(
            model_name='placetype',
            name='placeid',
        ),
        migrations.RemoveField(
            model_name='placewhen',
            name='placeid',
        ),
        migrations.AddField(
            model_name='place',
            name='id',
            field=models.AutoField(auto_created=True, default=-1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placedepiction',
            name='place_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='depictions', to='main.Place'),
        ),
        migrations.AddField(
            model_name='placedescription',
            name='place_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='main.Place'),
        ),
        migrations.AddField(
            model_name='placegeom',
            name='place_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='geoms', to='main.Place'),
        ),
        migrations.AddField(
            model_name='placelink',
            name='place_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='main.Place'),
        ),
        migrations.AddField(
            model_name='placename',
            name='place_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='main.Place'),
        ),
        migrations.AddField(
            model_name='placerelated',
            name='place_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='related', to='main.Place'),
        ),
        migrations.AddField(
            model_name='placetype',
            name='place_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='main.Place'),
        ),
        migrations.AddField(
            model_name='placewhen',
            name='place_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='whens', to='main.Place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='dataset',
            field=models.ForeignKey(db_column='dataset', on_delete=django.db.models.deletion.CASCADE, to='contribute.Dataset', to_field='label'),
        ),
    ]
